substitutions:
  friendly_name: Coffee Grinder
  device_name: coffee-grinder

packages:
  esphome: !include base/esp8266.template.yaml
  common: !include base/common.template.yaml

# Device Specific Config

uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: power_button
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "${friendly_name} Status"

sensor:
  - platform: cse7766
    current:
      name: "${friendly_name} Current"
      accuracy_decimals: 1
      filters:
        - throttle_average: 1s
    voltage:
      name: "${friendly_name} Voltage"
      accuracy_decimals: 1
      filters:
        - throttle_average: 1s
    power:
      name: "${friendly_name} Power"
      accuracy_decimals: 1
      filters:
        - throttle_average: 1s
      id: my_power
  # - platform: total_daily_energy
  #   name: "${friendly_name} Daily Energy"
  #   power_id: my_power

switch:
  - platform: gpio
    name: "${friendly_name}"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_OFF

status_led:
  pin: GPIO13
