substitutions:
  friendly_name: Holmes Tower
  device_name: holmes_fan

packages:
  esphome: !include base/esp8266.template.yaml
  common: !include base/common.template.yaml

time:
  - platform: homeassistant
    id: the_time
  # - platform: sntp
  #   id: the_time
  #   timezone: America/Chicago
  #   servers:
  #     - 10.2.1.1
  #     - 192.168.1.1
uart:
  baud_rate: 9600
  rx_pin: GPIO13
  tx_pin: GPIO15

tuya:
  time_id: the_time

fan:
  - platform: tuya
    name: Fan
    switch_datapoint: 1
    speed_datapoint: 3
    oscillation_datapoint: 5
    speed_count: 3
    restore_mode: RESTORE_DEFAULT_OFF

select:
  - platform: tuya
    name: Fan Mode
    id: fan_mode
    enum_datapoint: 2
    icon: 'mdi:wind-power'
    options:
      0: "None"
      1: Breeze
      2: Sleep

number:
  - platform: tuya
    name: Fan Sleep Timer
    number_datapoint: 22
    min_value: 0
    max_value: 15
    step: 1
    unit_of_measurement: hours
    entity_category: config
    icon: 'mdi:fan-clock'

switch:
  - platform: template
    name: Breeze Mode
    lambda: 'return id(fan_mode).active_index() == 1;'
    turn_on_action:
        - select.set_index: 
            id: fan_mode
            index: 1
    turn_off_action:
        - select.set_index: 
            id: fan_mode
            index: 0
  - platform: template
    name: Sleep Mode
    lambda: 'return id(fan_mode).active_index() == 2;'
    turn_on_action:
        - select.set_index: 
            id: fan_mode
            index: 2
    turn_off_action:
        - select.set_index: 
            id: fan_mode
            index: 0
#   - platform: tuya
#     name: Fan Oscillation
#     restore_mode: RESTORE_DEFAULT_OFF
#     entity_category: config
#     icon: 'mdi:arrow-oscillating'
#     switch_datapoint: 5