substitutions:
  friendly_name: Soundbar IR
esphome:
  name: soundbar-ir
esp32:
  board: m5stack-atom

logger:
  level: INFO
# packages:
#   common: !include base/common.template.yaml

remote_receiver:
  pin: 
    number: GPIO26
    inverted: True
  dump: nec
  # filter: 100us
