substitutions:
  name: home-assistant-voice-0972ec
  friendly_name: Kitchen Speaker
packages:
  Nabu Casa.Home Assistant Voice PE: github://esphome/home-assistant-voice-pe/home-assistant-voice.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret ha_voice_pe_kitchen_enc
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
