substitutions:
  friendly_name: Outside Plug
  device_name: outside-plug

packages:
  esphome: !include base/esp8266.template.yaml
  common: !include base/common.template.yaml

switch:
  - platform: gpio
    pin: 13
    name: "Outside Plug"
    id: relay

binary_sensor:
  - platform: gpio
    pin: 4
    id: power_button
    filters:
      - delayed_on: 10ms
    on_press:
      then:
        - switch.toggle: relay