substitutions:
  friendly_name: Robovac 35C
  device_name: robovac
esphome:
  name: ${device_name}

esp8266:
  board: esp01_1m

packages:
  common: !include common.template.yaml

wifi:
  fast_connect: true

uart:
  rx_pin: GPIO13
  tx_pin: GPIO15
  baud_rate: 115200

time:
  - platform: homeassistant
    id: ha_time

tuya:
  time_id: ha_time
  on_datapoint_update: 
    - sensor_datapoint: 15
      datapoint_type: enum
      then:
        - text_sensor.template.publish:
            id: text_status
            state: !lambda |-
              switch(x) {
                case 0: return "cleaning";
                case 1: return "paused";
                case 2: return "idle";
                case 3: return "docked";
                case 4: return "returning";
                case 5: return "returning";
                default: return "error";
              };
    - sensor_datapoint: 106
      datapoint_type: enum
      then:
        - text_sensor.template.publish:
            id: text_error
            state: !lambda |-
              switch(x) {
                case 0: return "";
                case 1: return "Stuck";
                case 2: return "Bumper";
                case 3: return "Sensors";
                case 4: return "Battery";
                case 5: return "Wheel";
                case 6: return "Brush";
                case 7: return "Fan";
                case 8: return "Roller";
                default: return "Error";
              };
switch:
  - platform: tuya
    name: ${friendly_name} Play/Pause
    switch_datapoint: 2
  - platform: tuya
    id: switch_findme
    switch_datapoint: 103
  - platform: tuya
    id: switch_gohome
    switch_datapoint: 101
binary_sensor:
  - platform: tuya
    name: ${friendly_name} Power
    sensor_datapoint: 1
    entity_category: diagnostic
button:
  - platform: template
    name: ${friendly_name} Go Home
    on_press:
      - switch.turn_on: switch_gohome
  - platform: template
    name: ${friendly_name} Locate Vacuum
    entity_category: diagnostic
    on_press:
      - switch.turn_on: switch_findme
      - delay: 10s
      - switch.turn_off: switch_findme
sensor:
  - platform: tuya
    name: ${friendly_name} Battery
    sensor_datapoint: 104
    device_class: battery
    unit_of_measurement: '%'
    accuracy_decimals: 0
    state_class: total

  # - platform: tuya
  #   name: ${friendly_name} DP3
  #   sensor_datapoint: 3
text_sensor:
  - platform: template
    name: ${friendly_name} Status
    id: text_status
    entity_category: diagnostic
  - platform: template
    name: ${friendly_name} Error
    id: text_error
    entity_category: diagnostic
select:
  - platform: "tuya"
    name: ${friendly_name} Fan Speed
    enum_datapoint: 102
    entity_category: config
    options:
      0: Standard
      1: BoostIQ
      2: Max
      3: 'Off'
  - platform: "tuya"
    name: ${friendly_name} Mode
    enum_datapoint: 5
    options:
      0: Auto
      1: Quick
      2: Spot
      3: Edge
      4: Stop
