# Disable logging
logger:
  baud_rate: 0

packages:
  wifi: !include wifi.inc.yaml
  time: !include time.inc.yaml
  ota: !include ota.inc.yaml
  api: !include api.inc.yaml

captive_portal:

button:
  - platform: safe_mode
    name: "${friendly_name} Restart in Safe Mode"
    internal: true

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
    internal: true

# sensor:
#   - platform: wifi_signal
#     name: "${friendly_name} WiFi Signal"
#     update_interval: 60s
#     internal: true